Repository team-yello/YELLO-Server, pull requests merged in 2023-09, with the labels that each got.

#281 YEL-132 [hotfix] 회원가입 에러 처리 - DeviceToken 처리
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/global/common/dto/MultiReadHttpServletRequest.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/exception/ExceptionHandlerFilter.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
Labels: fix, 의제🩳

#282 YEL-132 [deploy] 회원가입 에러 처리 - DeviceToken 처리
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/dto/MultiReadHttpServletRequest.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/exception/ExceptionHandlerFilter.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#283 YEL-132 [deploy] 회원가입 에러 처리 - DeviceToken 처리
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/dto/MultiReadHttpServletRequest.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/exception/ExceptionHandlerFilter.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#285 YEL-132 [deploy] repositoryImpl @transactional 제거
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
Labels: 의제🩳, 배포 🚀

#286 YEL-132 [deploy] repositoryImpl @transactional 제거
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
Labels: 의제🩳, 배포 🚀

#287 YEL-148 [fix] decode payload
  build.gradle
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
Labels: feat, 현정👕

#288 YEL-150 [fix] Slack 메세지에 Header 및 에러 class 추가
  build.gradle
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/main/java/com/yello/server/global/common/dto/MultiReadHttpServletRequest.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
Labels: fix, 의제🩳

#289 YEL-150 [deploy] Slack 메세지에 Header 및 에러 class 추가
  build.gradle
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/dto/MultiReadHttpServletRequest.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
Labels: 의제🩳, 배포 🚀

#291 YEL-150 [fix] 구독 중 키워드 확인시 포인트 차감 수정
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: fix, 의제🩳

#292 YEL-150 [deploy] 구독 중 키워드 확인시 포인트 차감 수정
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#293 YEL-151 [feat] 어드민 로그인 간소화
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminLoginRequest.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminLoginResponse.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/service/UserManager.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/test/java/com/yello/server/domain/user/FakeUserManager.java
Labels: feat, 의제🩳

#294 YEL-151 [feat] 어드민 로그인 간소화
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminLoginRequest.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminLoginResponse.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/service/UserManager.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/test/java/com/yello/server/domain/user/FakeUserManager.java
Labels: feat, 의제🩳

#295 YEL-152 [fix] 구글 구독시 열람권 3개 추가
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
Labels: fix, 의제🩳

#296 YEL-153 [fix] 학과친구 학교친구 추천으로 수정
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: fix, 현정👕

#297 YEL-152 [deploy] 구글 구독시 열람권 3개 추가
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#298 YEL-152 [deploy] 1.1.91v
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#299 YEL-158 [feat] 어드민 유저 디테일 조회 수정 및 어드민 비밀번호 변경
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminUserDetailRequest.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserDetailResponse.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: feat, 의제🩳

#300 YEL-158 [deploy] 어드민 유저 디테일 조회 수정 및 어드민 비밀번호 변경
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminUserDetailRequest.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserDetailResponse.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: feat, 의제🩳

#301 YEL-158 [deploy] v1.1.92
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminUserDetailRequest.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserDetailResponse.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#302 YEL-159 [feat] 어드민 이름 검색 추가
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/exception/UserAdminBadRequestException.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: feat, 의제🩳

#303 YEL-159 [feat] 어드민 이름 검색 추가
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/exception/UserAdminBadRequestException.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: feat, 배포 🚀

#304 YEL-159 [deploy] v1.193
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/exception/UserAdminBadRequestException.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#305 YEL-161 [feat] 회원가입 슬랙 알림 추가
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/infrastructure/slack/annotation/SlackSignUpNotification.java
  src/main/java/com/yello/server/infrastructure/slack/aspect/SlackSignUpNotificationAspect.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: feat, 의제🩳

#306 YEL-161 [deploy] 회원가입 슬랙 알림 추가
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/infrastructure/slack/annotation/SlackSignUpNotification.java
  src/main/java/com/yello/server/infrastructure/slack/aspect/SlackSignUpNotificationAspect.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#307 YEL-161 [deploy] v1.194
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/infrastructure/slack/annotation/SlackSignUpNotification.java
  src/main/java/com/yello/server/infrastructure/slack/aspect/SlackSignUpNotificationAspect.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 의제🩳, 배포 🚀

#308 YEL-154 [feat] apple notification - 구독 취소한 경우
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadDataVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadSummaryVO.java
  src/main/java/com/yello/server/domain/purchase/dto/request/AppleNotificationRequest.java
  src/main/java/com/yello/server/domain/purchase/dto/response/AppleNotificationResponse.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: feat, 현정👕

#309 YEL-154 [develop] apple notification 개발 서버 배포
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadDataVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadSummaryVO.java
  src/main/java/com/yello/server/domain/purchase/dto/request/AppleNotificationRequest.java
  src/main/java/com/yello/server/domain/purchase/dto/response/AppleNotificationResponse.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: 현정👕, 배포 🚀

#310 YEL-154 [fix] json parse 수정
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadDataVO.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
Labels: fix, feat, 현정👕

#312 YEL-154 [develop] 개발 서버 배포
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadDataVO.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
Labels: 현정👕, 배포 🚀

#313 YEL-154 [fix] decode 수정
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
Labels: fix, 현정👕

#314 YEL-154 [develop] 배포
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
Labels: 현정👕, 배포 🚀

#315 YEL-154 [fix] json null 처리
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
Labels: fix, 현정👕

#316 YEL-154 [develop]
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
Labels: 현정👕, 배포 🚀

#317 YEL-154 [feat] 에러 분기처리
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
Labels: fix, 현정👕

#318 YEL-154 [develop] apple 분기처리 배포
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
Labels: 현정👕, 배포 🚀

#319 YEL-154 [fix] test notification 수정
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: fix, 현정👕

#320 YEL-154 [develop] 서버 배포
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: 현정👕, 배포 🚀

#322 YEL-154, 153 [deploy] v1.195
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadDataVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadSummaryVO.java
  src/main/java/com/yello/server/domain/purchase/dto/request/AppleNotificationRequest.java
  src/main/java/com/yello/server/domain/purchase/dto/response/AppleNotificationResponse.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: 배포 🚀

#323 YEL-155 [feat] apple refund 처리
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
  src/test/java/com/yello/server/domain/user/small/UserTest.java
Labels: feat, 현정👕

#324 YEL-155 [develop] 개발 서버 배포
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
  src/test/java/com/yello/server/domain/user/small/UserTest.java
Labels: 현정👕, 배포 🚀

#325 YEL-162 [feat] 투표 수정사항 반영
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteManager.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
  src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
  src/test/java/com/yello/server/domain/vote/medium/VoteControllerTest.java
Labels: feat, 현정👕

#326 YEL-162 [develop] 투표수정사항 배포
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteManager.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
  src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
  src/test/java/com/yello/server/domain/vote/medium/VoteControllerTest.java
Labels: 현정👕, 배포 🚀

#327 YEL-162 [deploy] v1.196
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteManager.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
  src/test/java/com/yello/server/domain/user/small/UserTest.java
  src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
  src/test/java/com/yello/server/domain/vote/medium/VoteControllerTest.java
Labels: 현정👕, 배포 🚀

#335 YEL-155 [fix] revert
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
  src/test/java/com/yello/server/domain/user/small/UserTest.java
Labels: feat, 현정👕

#338 YEL-163 [feat] 어드민 투표 API 구현
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminQuestionVoteContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminQuestionVoteRequest.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionDetailResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserContentVO.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
  src/test/java/com/yello/server/domain/question/FakeQuestionRepository.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
  src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
Labels: feat, 의제🩳

#339 YEL-163 [deploy] 어드민 투표 API 구현
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminQuestionVoteContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminQuestionVoteRequest.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionDetailResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserContentVO.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
  src/test/java/com/yello/server/domain/question/FakeQuestionRepository.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
  src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
Labels: 의제🩳, test, 배포 🚀

#340 YEL-163 [deploy] v1.197
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminQuestionVoteContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/request/AdminQuestionVoteRequest.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionDetailResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserContentVO.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
  src/test/java/com/yello/server/domain/question/FakeQuestionRepository.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
  src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
Labels: 의제🩳, 배포 🚀

#341 YEL-163 [feat] 대학생, 고등학생 구분
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/response/ClassNameSearchResponse.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/friend/dto/response/FriendResponse.java
  src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendVO.java
  src/main/java/com/yello/server/domain/group/entity/School.java
  src/main/java/com/yello/server/domain/group/entity/SchoolType.java
  src/main/java/com/yello/server/domain/group/entity/SchoolTypeConverter.java
  src/main/java/com/yello/server/domain/group/repository/SchoolJpaRepository.java
  src/main/java/com/yello/server/domain/group/repository/SchoolRepository.java
  src/main/java/com/yello/server/domain/group/repository/SchoolRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/dto/response/UserDetailResponse.java
  src/main/java/com/yello/server/domain/user/dto/response/UserResponse.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/test/java/com/yello/server/domain/authorization/medium/AuthControllerTest.java
  src/test/java/com/yello/server/domain/group/FakeSchoolRepository.java
Labels: feat, 현정👕

#342 YEL-163 [feat] 대학생, 고등학생 구분
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/response/ClassNameSearchResponse.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/friend/dto/response/FriendResponse.java
  src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendVO.java
  src/main/java/com/yello/server/domain/group/entity/School.java
  src/main/java/com/yello/server/domain/group/entity/SchoolType.java
  src/main/java/com/yello/server/domain/group/entity/SchoolTypeConverter.java
  src/main/java/com/yello/server/domain/group/repository/SchoolJpaRepository.java
  src/main/java/com/yello/server/domain/group/repository/SchoolRepository.java
  src/main/java/com/yello/server/domain/group/repository/SchoolRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/dto/response/UserDetailResponse.java
  src/main/java/com/yello/server/domain/user/dto/response/UserResponse.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/test/java/com/yello/server/domain/authorization/medium/AuthControllerTest.java
  src/test/java/com/yello/server/domain/group/FakeSchoolRepository.java
Labels: 현정👕, 배포 🚀

#346 YEL-166 [fix] 내림차순 정렬
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
Labels: fix, 현정👕

#347 YEL-169 [fix] notification 수정
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationCustomMessage.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
Labels: fix, 현정👕

#350 YEL-170 [feat] apple notification slack webhook
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
  src/main/java/com/yello/server/infrastructure/slack/annotation/SlackApplePurchaseNotification.java
  src/main/java/com/yello/server/infrastructure/slack/aspect/SlackApplePurchaseNotificationAspect.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
Labels: feat, 현정👕

#351 YEL-170 [feat] apple notification slack webhook
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
  src/main/java/com/yello/server/infrastructure/slack/annotation/SlackApplePurchaseNotification.java
  src/main/java/com/yello/server/infrastructure/slack/aspect/SlackApplePurchaseNotificationAspect.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
Labels: 현정👕, 배포 🚀

#352 YEL-170 [modify] slack webhook request body 값 수정
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/infrastructure/slack/dto/response/SlackAppleNotificationResponse.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: modify, 현정👕

#353 YEL-170 [modify] slack webhook request body 값 수정
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/infrastructure/slack/dto/response/SlackAppleNotificationResponse.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: 현정👕, develop

#354 YEL-171 [feat] apple 구독 취소, 만료, 갱신 로직 구현
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePurchaseVO.java
  src/main/java/com/yello/server/domain/purchase/dto/response/AppleJwsTransactionResponse.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: feat

#355 YEL-171 [feat] apple 로직 구현 개발 서버 배포
  src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePurchaseVO.java
  src/main/java/com/yello/server/domain/purchase/dto/response/AppleJwsTransactionResponse.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
Labels: 현정👕, develop
