Repository team-yello/YELLO-Server, pull requests merged in 2023-06, with the labels that each got.

#3 [YEL-2/setting] 프로젝트 초기 세팅 재구성
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .gitignore
  appspec.yml
  build.gradle
  deploy.sh
  docker/Dockerfile
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  src/main/java/com/yello/server/Repository/UserRepository.java
  src/main/java/com/yello/server/ServerApplication.java
  src/main/java/com/yello/server/common/ErrorCode.java
  src/main/java/com/yello/server/common/SuccessCode.java
  src/main/java/com/yello/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/configuration/JpaConfiguration.java
  src/main/java/com/yello/server/configuration/QueryDslConfiguration.java
  src/main/java/com/yello/server/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/configuration/SwaggerConfiguration.java
  src/main/java/com/yello/server/controller/HealthCheckController.java
  src/main/java/com/yello/server/controller/UserController.java
  src/main/java/com/yello/server/dto/ApiResponse.java
  src/main/java/com/yello/server/dto/request/UserRequestDto.java
  src/main/java/com/yello/server/dto/user/request/UserRequest.java
  src/main/java/com/yello/server/entity/user/User.java
  src/main/java/com/yello/server/exception/BadRequestException.java
  src/main/java/com/yello/server/exception/ConflictException.java
  src/main/java/com/yello/server/exception/CustomException.java
  src/main/java/com/yello/server/exception/NotFoundException.java
  src/main/java/com/yello/server/exception/UnauthorizedException.java
  src/main/resources/applicaion.yaml
Labels: enhancement

#4 [YEL-2/setting] 프로젝트 초기 세팅
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .gitignore
  appspec.yml
  build.gradle
  deploy.sh
  docker/Dockerfile
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  src/main/java/com/yello/server/Repository/UserRepository.java
  src/main/java/com/yello/server/ServerApplication.java
  src/main/java/com/yello/server/common/ErrorCode.java
  src/main/java/com/yello/server/common/SuccessCode.java
  src/main/java/com/yello/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/configuration/JpaConfiguration.java
  src/main/java/com/yello/server/configuration/QueryDslConfiguration.java
  src/main/java/com/yello/server/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/configuration/SwaggerConfiguration.java
  src/main/java/com/yello/server/controller/HealthCheckController.java
  src/main/java/com/yello/server/controller/UserController.java
  src/main/java/com/yello/server/dto/ApiResponse.java
  src/main/java/com/yello/server/dto/request/UserRequestDto.java
  src/main/java/com/yello/server/dto/user/request/UserRequest.java
  src/main/java/com/yello/server/entity/user/User.java
  src/main/java/com/yello/server/exception/BadRequestException.java
  src/main/java/com/yello/server/exception/ConflictException.java
  src/main/java/com/yello/server/exception/CustomException.java
  src/main/java/com/yello/server/exception/NotFoundException.java
  src/main/java/com/yello/server/exception/UnauthorizedException.java
  src/main/resources/applicaion.yaml
Labels: enhancement

#10 [YEL-14/feat] entity 개발
  src/main/java/com/yello/server/ServerApplication.java
  src/main/java/com/yello/server/dto/ApiResponse.java
  src/main/java/com/yello/server/dto/user/request/UserRequest.java
  src/main/java/com/yello/server/entity/cooldown/Cooldown.java
  src/main/java/com/yello/server/entity/cooldown/CooldownRepository.java
  src/main/java/com/yello/server/entity/friend/Friend.java
  src/main/java/com/yello/server/entity/friend/FriendRepository.java
  src/main/java/com/yello/server/entity/group/School.java
  src/main/java/com/yello/server/entity/group/SchoolRepository.java
  src/main/java/com/yello/server/entity/keyword/Keyword.java
  src/main/java/com/yello/server/entity/keyword/KeywordRepository.java
  src/main/java/com/yello/server/entity/question/Question.java
  src/main/java/com/yello/server/entity/question/QuestionRepository.java
  src/main/java/com/yello/server/entity/user/User.java
  src/main/java/com/yello/server/entity/user/UserRepository.java
  src/main/java/com/yello/server/entity/vote/Vote.java
  src/main/java/com/yello/server/entity/vote/VoteRepository.java
Labels: feat

#11 YEL-23 [feat] Redis 설정 추가
  build.gradle
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  src/main/java/com/yello/server/configuration/RedisConfiguration.java
  src/main/java/com/yello/server/controller/HealthCheckController.java
Labels: feat, setting

#12 YEL-23 [feat] Redis 설정 추가
  build.gradle
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  src/main/java/com/yello/server/configuration/RedisConfiguration.java
  src/main/java/com/yello/server/controller/HealthCheckController.java
Labels: add

#13 YEL-23 [setting] 레디스 설정에 따른 deploy.sh 수정
  scripts/deploy.sh
Labels: setting
