Repository team-yello/YELLO-Server, pull requests merged in 2023-08, with the labels that each got.

#133 YEL-79 [chore] 개발 서버 분리
  .github/workflows/deploy-test.yml
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownJpaRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
  src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/group/repository/SchoolJpaRepository.java
  src/main/java/com/yello/server/domain/group/repository/SchoolRepository.java
  src/main/java/com/yello/server/domain/group/repository/SchoolRepositoryImpl.java
  src/main/java/com/yello/server/domain/keyword/entity/KeywordRepository.java
  src/main/java/com/yello/server/domain/keyword/repository/KeywordJpaRepository.java
  src/main/java/com/yello/server/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/yello/server/domain/keyword/repository/KeywordRepositoryImpl.java
  src/main/java/com/yello/server/domain/pay/controller/PayController.java
  src/main/java/com/yello/server/domain/pay/entity/PayRepository.java
  src/main/java/com/yello/server/domain/pay/repository/PayJpaRepository.java
  src/main/java/com/yello/server/domain/pay/repository/PayRepository.java
  src/main/java/com/yello/server/domain/pay/repository/PayRepositoryImpl.java
  src/main/java/com/yello/server/domain/pay/service/PayService.java
  src/main/java/com/yello/server/domain/pay/sevice/PayService.java
  src/main/java/com/yello/server/domain/pay/sevice/PayServiceImpl.java
  src/main/java/com/yello/server/domain/question/entity/QuestionRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionJpaRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/entity/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/domain/user/service/UserServiceImpl.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/test/java/com/yello/server/integration/friend/FriendControllerTest.java
  src/test/java/com/yello/server/small/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/small/friend/FakeFriendRepository.java
  src/test/java/com/yello/server/small/user/FakeUserRepository.java
  src/test/java/com/yello/server/small/user/UserServiceTest.java
  src/test/java/com/yello/server/small/vote/FakeVoteRepository.java
Labels: 세훈🧦, 배포 🚀

#132 YEL-86 [test] Friend 서비스 small 테스트 코드
  src/main/java/com/yello/server/domain/friend/dto/request/KakaoRecommendRequest.java
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/test/java/com/yello/server/small/friend/FakeFriendRepository.java
  src/test/java/com/yello/server/small/friend/FriendServiceTest.java
Labels: 세훈🧦, test

#135 YEL-80 [hotfix] Update ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
Labels: fix, 의제🩳

#136 YEL-88 [feat] 푸시 알림 구현
  build.gradle
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteCreateResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/firebase/configuration/FirebaseConfiguration.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
  src/main/java/com/yello/server/infrastructure/firebase/manager/FCMManager.java
  src/main/java/com/yello/server/infrastructure/firebase/manager/FCMManagerImpl.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
  src/main/java/com/yello/server/infrastructure/redis/exception/RedisNotFoundException.java
  src/main/java/com/yello/server/infrastructure/redis/repository/TokenRepositoryImpl.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/group/FakeSchoolRepository.java
  src/test/java/com/yello/server/small/domain/keyword/FakeKeywordRepository.java
  src/test/java/com/yello/server/small/domain/question/FakeQuestionRepository.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
  src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
  src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
  src/test/java/com/yello/server/small/global/firebase/FakeFcmManger.java
  src/test/java/com/yello/server/small/global/firebase/NotificationFcmServiceTest.java
  src/test/java/com/yello/server/small/global/redis/FakeTokenRepository.java
Labels: feat, add, 세훈🧦, test

#138 YEL-88 [feat] 푸시 알림 구현
  .github/workflows/deploy-test.yml
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteCreateResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/firebase/configuration/FirebaseConfiguration.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
  src/main/java/com/yello/server/infrastructure/firebase/manager/FCMManager.java
  src/main/java/com/yello/server/infrastructure/firebase/manager/FCMManagerImpl.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
  src/main/java/com/yello/server/infrastructure/redis/exception/RedisNotFoundException.java
  src/main/java/com/yello/server/infrastructure/redis/repository/TokenRepositoryImpl.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/group/FakeSchoolRepository.java
  src/test/java/com/yello/server/small/domain/keyword/FakeKeywordRepository.java
  src/test/java/com/yello/server/small/domain/question/FakeQuestionRepository.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
  src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
  src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
  src/test/java/com/yello/server/small/global/firebase/FakeFcmManger.java
  src/test/java/com/yello/server/small/global/firebase/NotificationFcmServiceTest.java
  src/test/java/com/yello/server/small/global/redis/FakeTokenRepository.java
Labels: feat, add, 세훈🧦, test, 배포 🚀

#142 YEL-90 [feat] entity 수정 반영
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/user/entity/Subscribe.java
  src/main/java/com/yello/server/domain/user/entity/SubscribeConverter.java
  src/main/java/com/yello/server/domain/user/entity/User.java
Labels: feat, 현정👕

#144 YEL-88 [update] User 엔티티 변경에 따른 푸시 알림 로직 수정
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/redis/repository/TokenRepository.java
  src/main/java/com/yello/server/infrastructure/redis/repository/TokenRepositoryImpl.java
  src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
  src/test/java/com/yello/server/small/global/firebase/NotificationFcmServiceTest.java
  src/test/java/com/yello/server/small/global/redis/FakeTokenRepository.java
Labels: modify, 세훈🧦

#143 YEL-90 [feat] subscribe 수정
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/user/entity/User.java
Labels: feat, 현정👕

#147 YEL-90 [feat] subscribe, minute
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
  src/main/java/com/yello/server/domain/user/entity/User.java
Labels: feat, 현정👕

#163 YEL-93 [feat] 친구 검색 API 개발
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendResponse.java
  src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendVO.java
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/group/repository/SchoolJpaRepository.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
Labels: feat, 현정👕

#164 YEL-95 [develop] 배포
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendResponse.java
  src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendVO.java
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/group/repository/SchoolJpaRepository.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
Labels: 현정👕, develop

#165 YEL-97 [fix] 친구 투표 조회 API totalCount 필드 추가
  src/main/java/com/yello/server/domain/friend/dto/response/RecommendFriendResponse.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendResponse.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendVO.java
  src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
Labels: fix, 의제🩳

#166 YEL-99 [fix] 재로그인 여부 필드 추가
  src/main/java/com/yello/server/domain/authorization/dto/response/OAuthResponse.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
Labels: feat, 의제🩳

#167 YEL-93 [fix] pagination 수정
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
Labels: fix, 현정👕

#168 YEL-93 [develop] Develop
  src/main/java/com/yello/server/domain/authorization/dto/response/OAuthResponse.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/dto/response/RecommendFriendResponse.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendResponse.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendVO.java
  src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
  src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
Labels: 현정👕, develop

#169 YEL-101 [test] 친구 검색 test
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
Labels: 현정👕, test

#170 YEL-103 [feat] purchase entity 개발
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/entity/Gateway.java
  src/main/java/com/yello/server/domain/purchase/entity/GatewayConverter.java
  src/main/java/com/yello/server/domain/purchase/entity/ProductType.java
  src/main/java/com/yello/server/domain/purchase/entity/ProductTypeConverter.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
Labels: feat, 현정👕

#171 YEL-103 [develop] 개발서버로 배포
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/entity/Gateway.java
  src/main/java/com/yello/server/domain/purchase/entity/GatewayConverter.java
  src/main/java/com/yello/server/domain/purchase/entity/ProductType.java
  src/main/java/com/yello/server/domain/purchase/entity/ProductTypeConverter.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
Labels: 현정👕, 배포 🚀

#172 YEL-103 [hotfix] soft delete error 해결
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
Labels: fix, 현정👕

#173 YEL-103 [develop] 배포
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
Labels: 현정👕, 배포 🚀

#174 YEL-88 [feat] 40분 대기열 후 푸시 알림 전송
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/configuration/RabbitmqConfiguration.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/dto/response/VoteAvailableQueueResponse.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRabbitRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ConsumerRabbitmqService.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ConsumerService.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerRabbitmqService.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerService.java
Labels: feat, add, 세훈🧦

#176 YEL-106 [fix] unique 설정
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/friend/entity/Friend.java
  src/main/java/com/yello/server/domain/group/entity/School.java
  src/main/java/com/yello/server/domain/user/entity/User.java
Labels: fix, 의제🩳

#177 YEL-108 [feat] 친구 추가 로직 수정
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
Labels: fix, 현정👕

#178 YEL-108 [develop] 배포
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/friend/entity/Friend.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/group/entity/School.java
  src/main/java/com/yello/server/domain/user/entity/User.java
Labels: 현정👕, 배포 🚀

#179 YEL-108 [feat] apple util 생성
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceipt.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
Labels: feat, 현정👕

#180 YEL-107 [feat] 열람권 개수 추가
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
Labels: feat, 현정👕

#181 YEL-107 [feat] 열람권 추가 배포
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceipt.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
Labels: 현정👕, 배포 🚀

#182 YEL-96 [feat] 첫 쪽지 구현
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/question/entity/Question.java
  src/main/java/com/yello/server/domain/question/repository/QuestionJpaRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
  src/test/java/com/yello/server/small/domain/question/FakeQuestionRepository.java
Labels: feat, 의제🩳

#183 YEL-109 [feat] , 제거
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceipt.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
  src/test/java/com/yello/server/small/global/rabbitmq/FakeMessageQueueRepository.java
  src/test/java/com/yello/server/small/global/rabbitmq/FakeProducerService.java
Labels: feat, 의제🩳

#184 YEL-109 [deploy] , 제거 및 첫쪽지 배포
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/question/entity/Question.java
  src/main/java/com/yello/server/domain/question/repository/QuestionJpaRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
  src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/question/FakeQuestionRepository.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
  src/test/java/com/yello/server/small/global/rabbitmq/FakeMessageQueueRepository.java
  src/test/java/com/yello/server/small/global/rabbitmq/FakeProducerService.java
Labels: 의제🩳, 배포 🚀

#185 YEL-95 [feat] nameHint -3, 옐로팀 이름 수정
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
Labels: feat, 의제🩳

#186 YEL-95 [feat] nameHint -3, 옐로팀 이름 수정
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
Labels: feat, 의제🩳

#187 YEL-92 [feat] 투표 조회하기 구독여부 추가
  src/main/java/com/yello/server/domain/question/dto/response/QuestionForVoteResponse.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
Labels: feat, 현정👕

#188 YEL-112 [feat] 투표 상세 subscribe 필드 추가
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
Labels: feat, 의제🩳

#189 YEL-100 [fix] test CI 수정
  .github/workflows/test.yml
Labels: 의제🩳, test

#190 YEL-100 [deploy] test ci, 투표 상세 조회 subscribe, 구독시 포인트 두배
  .github/workflows/test.yml
  src/main/java/com/yello/server/domain/question/dto/response/QuestionForVoteResponse.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
Labels: 배포 🚀

#192 YEL-112 [staging] ENUM -> Boolean 수정
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
Labels: 의제🩳, 배포 🚀

#193 YEL-98 [feat] 구독 연장 유도 필요 여부 확인 API 추가
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/response/UserSubscribeNeededResponse.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/test/java/com/yello/server/small/domain/purchase/FakePurchaseRepository.java
  src/test/java/com/yello/server/small/domain/purchase/PurchaseTest.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
Labels: feat, 의제🩳

#194 YEL-114 [feat] deviceToken 업데이트 API 추가
  src/main/java/com/yello/server/domain/user/controller/UserController.java
  src/main/java/com/yello/server/domain/user/dto/request/UserDeviceTokenRequest.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/dto/EmptyObject.java
Labels: feat, 의제🩳

#195 YEL-115 [fix] 둘러보기에 첫쪽지 제외
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
Labels: fix, 의제🩳

#196 YEL-110 [fea] apple util, dto 생성
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/InAppVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ReceiptVO.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
Labels: feat, 현정👕

#197 YEL-113 [feat] 500에러 슬랙 알람 추가
  build.gradle
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/global/common/util/SlackUtil.java
  src/main/java/com/yello/server/global/configuration/ThreadPoolConfiguration.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 의제🩳

#198 YEL-110 [fix] ci 수정
  .github/workflows/test.yml
Labels: fix, 현정👕

#199 YEL-98 [deploy] 구독 연장 유도 필요 여부 확인 API 추가
  .github/workflows/test.yml
  build.gradle
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/InAppVO.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/ReceiptVO.java
  src/main/java/com/yello/server/domain/purchase/dto/response/UserSubscribeNeededResponse.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/controller/UserController.java
  src/main/java/com/yello/server/domain/user/dto/request/UserDeviceTokenRequest.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/dto/EmptyObject.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
  src/main/java/com/yello/server/global/common/util/SlackUtil.java
  src/main/java/com/yello/server/global/configuration/ThreadPoolConfiguration.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/test/java/com/yello/server/small/domain/purchase/FakePurchaseRepository.java
  src/test/java/com/yello/server/small/domain/purchase/PurchaseTest.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
Labels: 의제🩳, 배포 🚀

#203 YEL-118 [feat] 애플 결제 검증 구현
  .gitignore
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleOrderResponse.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleTransaction.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceipt.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
  src/main/java/com/yello/server/domain/purchase/entity/ProductType.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/exception/PurchaseException.java
  src/main/java/com/yello/server/domain/purchase/exception/PurchaseNotFoundException.java
  src/main/java/com/yello/server/domain/purchase/exception/SubscriptionConflictException.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/factory/TokenFactory.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 현정👕

#204 YEL-117 [develop] apple 결제 검증 배포
  .gitignore
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleOrderResponse.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleTransaction.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceipt.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
  src/main/java/com/yello/server/domain/purchase/entity/ProductType.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/exception/PurchaseException.java
  src/main/java/com/yello/server/domain/purchase/exception/PurchaseNotFoundException.java
  src/main/java/com/yello/server/domain/purchase/exception/SubscriptionConflictException.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/factory/TokenFactory.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: 현정👕, 배포 🚀

#205 YEL-88 [update] FCM Badge, Sound 추가
  src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/yello/server/infrastructure/firebase/manager/FCMManager.java
  src/main/java/com/yello/server/infrastructure/firebase/manager/FCMManagerImpl.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
  src/test/java/com/yello/server/small/global/firebase/FakeFcmManger.java
Labels: modify, 세훈🧦

#208 YEL-117 [develop] 구독 상태 제공 배포
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
Labels: 현정👕, 배포 🚀

#209 YEL-123 [feat] 이름 전체 공개 API 구현
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/RevealFullNameResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
Labels: feat, 현정👕

#210 YEL-123 [develop] 배포
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/RevealFullNameResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
Labels: 배포 🚀

#211 YEL-121 [refactor] 서비스 추상화 작업
  src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthManager.java
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/TokenJwtProvider.java
  src/main/java/com/yello/server/domain/authorization/service/TokenProvider.java
  src/main/java/com/yello/server/domain/friend/service/FriendManager.java
  src/main/java/com/yello/server/domain/friend/service/FriendManagerImpl.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/service/UserManager.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/service/VoteManager.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/manager/ConnectionManager.java
  src/main/java/com/yello/server/global/common/manager/ConnectionManagerImpl.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/authorization/FakeAuthManager.java
  src/test/java/com/yello/server/small/domain/authorization/FakeConnectionManager.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendManager.java
  src/test/java/com/yello/server/small/domain/user/FakeUserManager.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
  src/test/java/com/yello/server/small/domain/vote/FakeVoteManager.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
Labels: refactor, 세훈🧦

#212 YEL-121 [refactor] 서비스 추상화
  src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthManager.java
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/TokenJwtProvider.java
  src/main/java/com/yello/server/domain/authorization/service/TokenProvider.java
  src/main/java/com/yello/server/domain/friend/service/FriendManager.java
  src/main/java/com/yello/server/domain/friend/service/FriendManagerImpl.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/service/UserManager.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/service/VoteManager.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/manager/ConnectionManager.java
  src/main/java/com/yello/server/global/common/manager/ConnectionManagerImpl.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/authorization/FakeAuthManager.java
  src/test/java/com/yello/server/small/domain/authorization/FakeConnectionManager.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendManager.java
  src/test/java/com/yello/server/small/domain/user/FakeUserManager.java
  src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
  src/test/java/com/yello/server/small/domain/vote/FakeVoteManager.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
Labels: refactor, 세훈🧦, 배포 🚀

#213 YEL-109 [feat] Google Rest Util 추가
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .gitignore
  build.gradle
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/main/java/com/yello/server/global/common/dto/response/GoogleInAppGetResponse.java
  src/main/java/com/yello/server/global/common/dto/response/GoogleTokenIssueResponse.java
  src/main/java/com/yello/server/global/common/entity/GoogleToken.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenJpaRepository.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenRepository.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenRepositoryImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
Labels: feat, 의제🩳

#214 YEL-109 [deploy] staging 1.0.7 배포
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .gitignore
  build.gradle
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/main/java/com/yello/server/global/common/dto/response/GoogleInAppGetResponse.java
  src/main/java/com/yello/server/global/common/dto/response/GoogleTokenIssueResponse.java
  src/main/java/com/yello/server/global/common/entity/GoogleToken.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenJpaRepository.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenRepository.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenRepositoryImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
Labels: 의제🩳, 배포 🚀

#216 YEL-78 [fix] 클라 QA 반영
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/main/java/com/yello/server/domain/vote/common/WeightedRandomFactory.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
Labels: fix, 현정👕

#217 YEL-78 [develop] 개발 서버에 배포
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/main/java/com/yello/server/domain/vote/common/WeightedRandomFactory.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
Labels: 배포 🚀

#218 YEL-78 [develop] 클라 수정사항 실서버에 배포
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/main/java/com/yello/server/domain/vote/common/WeightedRandomFactory.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
Labels: 배포 🚀

#219 YEL-104 [feat] 투표 이름 전체 조회 수정
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
Labels: fix, 현정👕

#220 YEL-124 [add] 푸시 알림 관련 도메인 로직 수정
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/NotificationType.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/dto/response/VoteAvailableQueueResponse.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRabbitRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerRabbitmqService.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/small/global/rabbitmq/FakeMessageQueueRepository.java
Labels: feat, add, modify, 세훈🧦, develop

#222 YEL-104 [feat] 친구 셔플 테스트
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
Labels: feat

#221 YEL-78 [develop] 개발 서버 배포
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/NotificationType.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/dto/response/VoteAvailableQueueResponse.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRabbitRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerRabbitmqService.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/global/rabbitmq/FakeMessageQueueRepository.java
Labels: 현정👕, 세훈🧦, 배포 🚀

#223 YEL-104 [develop] 실서버 배포
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/NotificationType.java
  src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
  src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/dto/response/VoteAvailableQueueResponse.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRabbitRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerRabbitmqService.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/global/rabbitmq/FakeMessageQueueRepository.java
Labels: 현정👕, 배포 🚀

#225 YEL-125 [depoly] test 1.0.8v
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/response/UserPurchaseInfoResponse.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
Labels: 의제🩳, 배포 🚀

#226 YEL-125 [deploy] 1.0.8v
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/response/UserPurchaseInfoResponse.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRabbitRepository.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ConsumerRabbitmqService.java
  src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerRabbitmqService.java
Labels: 배포 🚀

#227 YEL-95 [feat] 구글 구독 확인 API 구현
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/request/GoogleSubscriptionV2GetRequest.java
  src/main/java/com/yello/server/domain/purchase/dto/response/GoogleSubscriptionV2GetResponse.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/exception/GoogleBadRequestException.java
  src/main/java/com/yello/server/domain/purchase/exception/GoogleTokenNotFoundException.java
  src/main/java/com/yello/server/domain/purchase/exception/GoogleTokenServerErrorException.java
  src/main/java/com/yello/server/domain/purchase/exception/PurchaseConflictException.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/entity/GoogleToken.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenRepository.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenRepositoryImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
Labels: feat, 의제🩳

#228 YEL-95 [Deploy] test 1.0.9v 구글 구독 확인 API 구현
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/request/GoogleSubscriptionV2GetRequest.java
  src/main/java/com/yello/server/domain/purchase/dto/response/GoogleSubscriptionV2GetResponse.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/exception/GoogleBadRequestException.java
  src/main/java/com/yello/server/domain/purchase/exception/GoogleTokenNotFoundException.java
  src/main/java/com/yello/server/domain/purchase/exception/GoogleTokenServerErrorException.java
  src/main/java/com/yello/server/domain/purchase/exception/PurchaseConflictException.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/entity/GoogleToken.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenRepository.java
  src/main/java/com/yello/server/global/common/repository/GoogleTokenRepositoryImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
Labels: 배포 🚀

#229 YEL-104 [feat] refund 구현, verify 수정
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/request/AppleInAppRefundRequest.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/exception/AppleTokenServerErrorException.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/test/java/com/yello/server/small/domain/purchase/FakePurchaseRepository.java
Labels: feat, modify, 현정👕

#230 YEL-127 [feat] 구글 인앱 결제 검증 api 구현
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/request/GoogleInAppGetRequest.java
  src/main/java/com/yello/server/domain/purchase/dto/response/GoogleInAppV1GetResponse.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
Labels: feat, 의제🩳

#231 YEL-127 [deploy] test 1.0.91v 구글 인앱 결제 검증 api 구현
  src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
  src/main/java/com/yello/server/domain/purchase/dto/request/AppleInAppRefundRequest.java
  src/main/java/com/yello/server/domain/purchase/dto/request/GoogleInAppGetRequest.java
  src/main/java/com/yello/server/domain/purchase/dto/response/GoogleInAppV1GetResponse.java
  src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
  src/main/java/com/yello/server/domain/purchase/exception/AppleTokenServerErrorException.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
  src/test/java/com/yello/server/small/domain/purchase/FakePurchaseRepository.java
Labels: 의제🩳, 배포 🚀

#232 YEL-128 [fix] build 에러 수정
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
Labels: fix, 현정👕

#233 YEL-128 [feat] 서버 배포
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
Labels: 현정👕, 배포 🚀

#238 YEL-134 [test] 목데이터를 위한 테스트 유틸 클래스 작성 및 테스트 코드 수정
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/test/java/com/yello/server/small/domain/authorization/AuthManagerTest.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/friend/FriendManagerTest.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/purchase/PurchaseServiceTest.java
  src/test/java/com/yello/server/small/domain/user/UserManagerTest.java
  src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
  src/test/java/com/yello/server/small/domain/vote/VoteManagerTest.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
  src/test/java/com/yello/server/util/TestDataUtil.java
Labels: 세훈🧦, test

#239 YEL-135 [update] 푸시 알림 메세지 변경
  src/main/java/com/yello/server/domain/question/entity/Question.java
Labels: 세훈🧦

#240 YEL-134 [update] 푸시 알림 메세지 변경 및 테스트 코드 수정
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/question/entity/Question.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/test/java/com/yello/server/small/domain/authorization/AuthManagerTest.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/friend/FriendManagerTest.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/purchase/PurchaseServiceTest.java
  src/test/java/com/yello/server/small/domain/user/UserManagerTest.java
  src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
  src/test/java/com/yello/server/small/domain/vote/VoteManagerTest.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
  src/test/java/com/yello/server/util/TestDataUtil.java
Labels: refactor, 세훈🧦, test, 배포 🚀

#241 YEL-134 [update] 푸시 알림 메세지 변경 및 테스트 코드 수정
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/authorization/service/TokenJwtProvider.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/question/entity/Question.java
  src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
  src/test/java/com/yello/server/small/domain/authorization/AuthManagerTest.java
  src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
  src/test/java/com/yello/server/small/domain/friend/FriendManagerTest.java
  src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
  src/test/java/com/yello/server/small/domain/purchase/PurchaseServiceTest.java
  src/test/java/com/yello/server/small/domain/user/UserManagerTest.java
  src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
  src/test/java/com/yello/server/small/domain/vote/VoteManagerTest.java
  src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
  src/test/java/com/yello/server/util/TestDataUtil.java
Labels: refactor, 세훈🧦, test, 배포 🚀

#242 YEL-131 [fix] 투표리스트 조회시 옐로팀 제외
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
Labels: fix, 현정👕

#243 YEL-31 [develop] 개발서버 배포
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
Labels: 현정👕, 배포 🚀

#244 YEL-32 [develop] 투표리스트 옐로팀 제외
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
Labels: 현정👕, 배포 🚀

#245 YEL-111 [fix] 친구 검색시 빈값인 경우 빈배열 제공
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
Labels: modify, 현정👕

#246 YEL-138 [modify] 내 쪽지 count data 추가
  src/main/java/com/yello/server/domain/vote/dto/response/VoteCountVO.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
  src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
Labels: modify, 현정👕

#248 YEL-132 [hotfix] 상수처리
  .github/workflows/deploy-test.yml
  .github/workflows/deploy.yml
  src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
Labels: fix, 현정👕

#249 YEL-140 [modify] apple in app verify 로직 수정
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/util/AppleUtil.java
Labels: modify, 현정👕

#252 YEL-132 [hotfix] if문에서 case문으로 바꿈
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
Labels: feat, 의제🩳

#253 YEL-132 [deploy] test - 1.1.0v
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
Labels: test, 배포 🚀

#257 YEL-139 [test] 테스트 코드 추가 및 어색한 메서드명 수정
  .gitignore
  build.gradle
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/configuration/QueryDslConfiguration.java
  src/test/java/com/yello/server/domain/user/small/UserRepositoryTest.java
  src/test/java/com/yello/server/domain/user/small/UserTest.java
Labels: 세훈🧦, develop, test

#260 YEL-145 [fix] soft deleted 유저의 yelloId 중복 체크
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/test/java/com/yello/server/domain/authorization/FakeAuthManager.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: fix, 의제🩳

#261 YEL-144 [fix] apple 결제 json 오류 수정
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleOrderResponse.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
Labels: fix, 현정👕

#262 YEL-139 [test] 구글 결제 관련 명세서 수정
  src/docs/asciidoc/google.adoc
Labels: 세훈🧦, test

#263 YEL-139 [test] 구글 결제 관련 명세 수정 및 일부 코드 로직 수정
  src/docs/asciidoc/google.adoc
  src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/AppleOrderResponse.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
  src/test/java/com/yello/server/domain/authorization/FakeAuthManager.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: fix, 현정👕, 의제🩳, 세훈🧦, test, 배포 🚀

#266 YEL-146 [fix] 친구 삭제 500에러 수정
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
Labels: fix, 현정👕

#267 YEL-146 [test] apple 결제 검증 테스트
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/factory/TokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/java/com/yello/server/infrastructure/client/ApiWebClient.java
  src/main/java/com/yello/server/infrastructure/client/AppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakeAppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseRepository.java
  src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
  src/test/java/com/yello/server/domain/purchase/small/PurchaseServiceTest.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 현정👕, test

#269 YEL-146 [merge] 개발서버 배포
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/factory/TokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/java/com/yello/server/infrastructure/client/ApiWebClient.java
  src/main/java/com/yello/server/infrastructure/client/AppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakeAppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseRepository.java
  src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
  src/test/java/com/yello/server/domain/purchase/small/PurchaseServiceTest.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 배포 🚀

#270 YEL-147 [feat] admin 1차 구현
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminCooldownContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminCooldownResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserSearchResponse.java
  src/main/java/com/yello/server/domain/admin/entity/UserAdmin.java
  src/main/java/com/yello/server/domain/admin/exception/UserAdminNotFoundException.java
  src/main/java/com/yello/server/domain/admin/repository/UserAdminJpaRepository.java
  src/main/java/com/yello/server/domain/admin/repository/UserAdminRepository.java
  src/main/java/com/yello/server/domain/admin/repository/UserAdminRepositoryImpl.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownJpaRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/TimeFactory.java
  src/test/java/com/yello/server/domain/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: feat, 의제🩳

#271 YEL-148 [fix] apple verify 수정
  build.gradle
  src/main/java/com/yello/server/domain/purchase/dto/apple/TransactionInfoResponse.java
  src/main/java/com/yello/server/domain/purchase/dto/response/AppleJwsTransactionResponse.java
  src/main/java/com/yello/server/domain/purchase/exception/AppleBadRequestException.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/factory/TokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/client/ApiWebClient.java
  src/main/java/com/yello/server/infrastructure/client/AppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakeAppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
  src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
Labels: fix, 현정👕

#272 YEL-148 [merge] 개발서버 배포
  build.gradle
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminCooldownContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminCooldownResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserContentVO.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserResponse.java
  src/main/java/com/yello/server/domain/admin/dto/response/AdminUserSearchResponse.java
  src/main/java/com/yello/server/domain/admin/entity/UserAdmin.java
  src/main/java/com/yello/server/domain/admin/exception/UserAdminNotFoundException.java
  src/main/java/com/yello/server/domain/admin/repository/UserAdminJpaRepository.java
  src/main/java/com/yello/server/domain/admin/repository/UserAdminRepository.java
  src/main/java/com/yello/server/domain/admin/repository/UserAdminRepositoryImpl.java
  src/main/java/com/yello/server/domain/admin/service/AdminService.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownJpaRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
  src/main/java/com/yello/server/domain/purchase/dto/apple/TransactionInfoResponse.java
  src/main/java/com/yello/server/domain/purchase/dto/response/AppleJwsTransactionResponse.java
  src/main/java/com/yello/server/domain/purchase/exception/AppleBadRequestException.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
  src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/factory/TimeFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactory.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/infrastructure/client/ApiWebClient.java
  src/main/java/com/yello/server/infrastructure/client/AppleApiWebClient.java
  src/test/java/com/yello/server/domain/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/domain/purchase/FakeAppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
  src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: 현정👕, 배포 🚀

#276 YEL-148 [merge] 개발서버 배포
  .github/workflows/build.yml
  .github/workflows/deploy-test.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/main/resources/static/docs/check-vote-available.html
  src/main/resources/static/docs/google.html
Labels: 배포 🚀

#274 YEL-147 [feat] cors 설정
  src/main/java/com/yello/server/domain/admin/configuration/AdminWebConfig.java
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
Labels: 의제🩳, test

#277 YEL-148 [modify] apple token json 형식으로 변경
  gradlew
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/test/java/com/yello/server/domain/purchase/FakeAppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
Labels: modify, 현정👕

#278 YEL-148 [mege] 실서버 배포
  .github/workflows/deploy-test.yml
  .github/workflows/deploy.yml
  gradlew
  src/main/java/com/yello/server/domain/admin/configuration/AdminWebConfig.java
  src/main/java/com/yello/server/domain/admin/controller/AdminController.java
  src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
  src/test/java/com/yello/server/domain/purchase/FakeAppleApiWebClient.java
  src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
Labels: 배포 🚀

#280 YEL-149 [fix] 친구 검색하기 로직 수정
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/test/java/com/yello/server/domain/user/FakeUserRepository.java
Labels: fix, 현정👕
