Repository team-yello/YELLO-Server, pull requests merged in 2023-07, with the labels that each got.

#19 [YEL-17/feat] 투표 전체 조회 API 및 기타 리팩토링
  build.gradle
  src/main/java/com/yello/server/domain/cooldown/entity/CooldownRepository.java
  src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
  src/main/java/com/yello/server/domain/group/entity/SchoolRepository.java
  src/main/java/com/yello/server/domain/keyword/entity/KeywordRepository.java
  src/main/java/com/yello/server/domain/question/entity/QuestionRepository.java
  src/main/java/com/yello/server/domain/user/entity/Gender.java
  src/main/java/com/yello/server/domain/user/entity/Social.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/entity/UserRepository.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteContentVO.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendResponse.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteResponse.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/entity/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/HealthCheckController.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/common/dto/ApiResponse.java
  src/main/java/com/yello/server/global/common/dto/BaseResponse.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/TimeUtil.java
  src/main/java/com/yello/server/global/configuration/SwaggerConfiguration.java
Labels: feat, add, refactor

#20 YEL-22 [feat] 투표 상세 정보 조회 API 구현
  src/main/java/com/yello/server/domain/user/entity/Gender.java
  src/main/java/com/yello/server/domain/user/entity/Social.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendResponse.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteResponse.java
  src/main/java/com/yello/server/domain/vote/exception/VoteException.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/exception/BadRequestException.java
  src/main/java/com/yello/server/global/exception/ConflictException.java
  src/main/java/com/yello/server/global/exception/CustomException.java
  src/main/java/com/yello/server/global/exception/NotFoundException.java
  src/main/java/com/yello/server/global/exception/UnauthorizedException.java
Labels: feat, 세훈🧦

#21 YEL-33 [feat] 친구 추가하기 API 구현
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/entity/Friend.java
  src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/question/entity/Question.java
  src/main/java/com/yello/server/domain/user/entity/Gender.java
  src/main/java/com/yello/server/domain/user/entity/GenderConverter.java
  src/main/java/com/yello/server/domain/user/entity/Social.java
  src/main/java/com/yello/server/domain/user/entity/SocialConverter.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/entity/UserRepository.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteContentVO.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/configuration/SwaggerConfiguration.java
  src/test/java/com/yello/server/friend/FriendControllerTest.java
Labels: feat, 현정👕

#22 YEL-38 [update] Soft delete 처리를 위한 User 엔티티 수정
  src/main/java/com/yello/server/domain/user/entity/User.java
Labels: modify, 세훈🧦

#23 [YEL-17/update] 투표 조회 API 수정 사항 반영
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteContentVO.java
Labels: modify, 세훈🧦

#25 YEL-35 [feat] 친구 셔플 조회하기 API
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/dto/FriendResponse.java
  src/main/java/com/yello/server/domain/friend/dto/FriendsResponse.java
  src/main/java/com/yello/server/domain/friend/dto/response/FriendShuffleResponse.java
  src/main/java/com/yello/server/domain/friend/entity/Friend.java
  src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/exception/FriendException.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/group/entity/School.java
  src/main/java/com/yello/server/domain/user/exception/UserException.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/global/common/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/PaginationUtil.java
  src/test/java/com/yello/server/friend/FriendControllerTest.java
Labels: feat, 현정👕

#24 YEL-21 [feat] 내 친구 전체 조회 API 구현
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/dto/FriendResponse.java
  src/main/java/com/yello/server/domain/friend/dto/FriendsResponse.java
  src/main/java/com/yello/server/domain/friend/entity/Friend.java
  src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/group/entity/School.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/util/PaginationUtil.java
  src/test/java/com/yello/server/friend/FriendControllerTest.java
Labels: feat, add, modify, 세훈🧦

#30 YEL-30 [Feat] 포인트 사용시 keyword 확인 API 개발
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/KeywordCheckResponse.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/test/java/com/yello/server/integration/friend/FriendControllerTest.java
Labels: feat, 현정👕

#28 YEL-22 [update] 투표 응답값 변경에 따른 DTO 수정
  src/main/java/com/yello/server/domain/vote/dto/response/VoteContentVO.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteResponse.java
Labels: modify

#33 YEL-41 [feat] school recommend friend 조회 API
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/dto/response/FriendShuffleResponse.java
  src/main/java/com/yello/server/domain/friend/dto/response/RecommendFriendResponse.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/question/dto/response/YelloKeyword.java
  src/main/java/com/yello/server/domain/question/dto/response/YelloQuestion.java
  src/main/java/com/yello/server/domain/question/dto/response/YelloVoteResponse.java
  src/main/java/com/yello/server/domain/user/entity/UserRepository.java
  src/main/java/com/yello/server/domain/vote/dto/response/KeywordCheckResponse.java
  src/main/java/com/yello/server/global/common/util/PaginationUtil.java
  src/main/java/com/yello/server/global/common/util/TimeUtil.java
Labels: feat, 현정👕

#35 YEL-30 [update] update README.md
  README.md
Labels: docs, 현정👕

#34 YEL-42 [feat] 소셜 로그인 API 및 Authorization 구현
  build.gradle
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
  src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/KakaoTokenInfo.java
  src/main/java/com/yello/server/domain/authorization/dto/ServiceTokenVO.java
  src/main/java/com/yello/server/domain/authorization/dto/request/OAuthRequest.java
  src/main/java/com/yello/server/domain/authorization/dto/response/OAuthResponse.java
  src/main/java/com/yello/server/domain/authorization/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/yello/server/domain/authorization/exception/CustomAuthenticationException.java
  src/main/java/com/yello/server/domain/authorization/exception/ExpiredTokenException.java
  src/main/java/com/yello/server/domain/authorization/exception/InvalidTokenException.java
  src/main/java/com/yello/server/domain/authorization/exception/NotSignedInException.java
  src/main/java/com/yello/server/domain/authorization/exception/OAuthException.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/user/entity/UserRepository.java
  src/main/java/com/yello/server/global/common/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/dto/BaseResponse.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
  src/main/java/com/yello/server/global/configuration/RedisConfiguration.java
  src/main/java/com/yello/server/global/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/exception/ExceptionHandlerFilter.java
  src/main/java/com/yello/server/infrastructure/redis/configuration/RedisConfiguration.java
  src/main/java/com/yello/server/infrastructure/redis/exception/RedisException.java
Labels: feat, 세훈🧦

#27 YEL-26 [feat] 아이디 중복 확인 API
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/exception/AuthBadRequestException.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/user/entity/UserRepository.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 의제🩳

#36 YEL-30 [update] Update README.md
  README.md
Labels: docs, 현정👕

#37 YEL-30 [update] Update README.md
  README.md
Labels: docs, 현정👕

#38 YEL-36 [feat] 투표 생성하기 API 개발
  .gitignore
  src/main/java/com/yello/server/domain/question/exception/QuestionException.java
  src/main/java/com/yello/server/domain/question/service/QuestionService.java
  src/main/java/com/yello/server/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/domain/user/service/UserServiceImpl.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/request/CreateVoteRequest.java
  src/main/java/com/yello/server/domain/vote/dto/request/VoteAnswer.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 현정👕

#41 YEL-43 [fix] 투표리스트 조회 수정
  src/main/java/com/yello/server/ServerApplication.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteContentVO.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteKeyword.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteQuestionResponse.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteShuffleFriend.java
  src/main/java/com/yello/server/domain/question/entity/Question.java
  src/main/java/com/yello/server/domain/vote/common/WeightedRandom.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
Labels: modify, 현정👕

#39 YEL-28 [feat] 회원가입 API 개발
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
  src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/authorization/dto/response/SignUpResponse.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/group/exception/GroupNotFoundException.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/user/exception/UserConflictException.java
  src/main/java/com/yello/server/domain/user/service/UserServiceImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 의제🩳

#42 YEL-28 [feat] 인가 annotation 기능 추가
  src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/domain/authorization/configuration/WebMvcConfig.java
  src/main/java/com/yello/server/domain/authorization/exception/AuthNotFoundException.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/annotation/AccessTokenUser.java
  src/main/java/com/yello/server/global/common/annotation/AccessTokenUserResolver.java
Labels: feat, 의제🩳

#45 YEL-17 [update] AccessTokenUser를 이용한 인가 처리
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/user/service/UserServiceImpl.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/entity/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: modify, 세훈🧦

#46 YEL-32 [feat] kakao recommend friend list 조회
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/dto/request/KakaoRecommendRequest.java
  src/main/java/com/yello/server/domain/friend/dto/response/Friend.java
  src/main/java/com/yello/server/domain/friend/dto/response/KakaoFriendResponse.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/user/entity/UserRepository.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
Labels: feat, 현정👕

#47 YEL-44 [feat] update access token 적용
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
Labels: feat, 현정👕

#49 YEL-17 [chore] profile Image URL 필드 추가
  src/main/java/com/yello/server/domain/friend/dto/FriendResponse.java
  src/main/java/com/yello/server/domain/user/dto/UserResponse.java
Labels: modify, 세훈🧦

#52 YEL-45 [refactor] 코드 개선
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/user/controller/UserController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/annotation/AccessTokenUserResolver.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/TimeUtil.java
  src/main/java/com/yello/server/global/configuration/SwaggerConfiguration.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/exception/ExceptionHandlerFilter.java
Labels: refactor, 세훈🧦

#53 YEL-45 [refactor] 코드 개선
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/user/controller/UserController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/annotation/AccessTokenUserResolver.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/TimeUtil.java
  src/main/java/com/yello/server/global/configuration/SwaggerConfiguration.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/yello/server/global/exception/ExceptionHandlerFilter.java
Labels: refactor, 세훈🧦

#55 YEL-45 [update] VoteDetailResponse에 포인트 추가
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
Labels: 세훈🧦

#56 YEL-45 [update] VoteDetailResponse에 포인트 추가
  src/main/java/com/yello/server/domain/vote/dto/response/VoteContentVO.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
Labels: refactor, 세훈🧦

#50 YEL-31 [feat] 포인트로 이름 공개 API 개발
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/group/entity/School.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/RevealNameResponse.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/entity/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/exception/VoteForbiddenException.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 현정👕

#57 YEL-46 [modify] create vote response
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteCreateResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: feat, 현정👕

#58 YEL-47 [modify] modify point weight
  src/main/java/com/yello/server/domain/vote/common/WeightedRandom.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
Labels: feat, 현정👕

#51 YEL-27 [feat] 회원가입 추천 친구 리스트 API 구현
  database/school.json
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/KakaoTokenInfo.java
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoFriend.java
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoFriendsInfo.java
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoTokenInfo.java
  src/main/java/com/yello/server/domain/authorization/dto/request/OnBoardingFriendRequest.java
  src/main/java/com/yello/server/domain/authorization/dto/response/OnBoardingFriendResponse.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/group/entity/SchoolRepository.java
  src/main/java/com/yello/server/domain/user/entity/UserRepository.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/util/ListUtil.java
  src/main/java/com/yello/server/global/common/util/PaginationUtil.java
  src/main/java/com/yello/server/global/common/util/RestUtil.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 의제🩳

#59 YEL-25 [feat] 학교 학과 검색 API 구현
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/response/DepartmentSearchResponse.java
  src/main/java/com/yello/server/domain/authorization/dto/response/GroupNameSearchResponse.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/group/entity/School.java
  src/main/java/com/yello/server/domain/group/entity/SchoolRepository.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 의제🩳

#61 YEL-50 [hotfix] 잠시 case 바꿈
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoFriend.java
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoFriendsInfo.java
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoTokenInfo.java
Labels: fix

#62 YEL-50 [hotfix] 잠시 case 바꿈 (develop <- main)
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoFriend.java
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoFriendsInfo.java
  src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoTokenInfo.java
Labels: fix, 의제🩳

#63 YEL-28 [fix] kakao token 의존성 제거
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
Labels: fix, 의제🩳

#64 [YEL-51] 타이머 40분 추가, shuffle에 yelloId 추가
  src/main/java/com/yello/server/domain/friend/dto/response/FriendShuffleResponse.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/TimeUtil.java
Labels: feat, 현정👕

#66 YEL-52 [fix] 내 투표 전체 조회 API Response 수정
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: fix, 세훈🧦

#67 YEL-52 [fix] 내 투표 전체 조회 API Response 수정
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: fix

#69 YEL-51 [hotfix] 학교 그룹 데이터 filter
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
Labels: fix, 현정👕

#70 YEL-7 [merge] 서버 배포
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
Labels: 현정👕, develop

#71 YEL-45 [hotfix] 친구 전체 조회 로직 수정
  .github/CODEOWNERS
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
Labels: fix, 세훈🧦

#73 YEL-7 [develop] 서버 배포
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/util/PaginationUtil.java
Labels: 현정👕, develop

#74 YEL-25 [hotfix] totalCount 수정
  src/main/java/com/yello/server/domain/authorization/dto/response/DepartmentSearchResponse.java
  src/main/java/com/yello/server/domain/authorization/dto/response/GroupNameSearchResponse.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/group/entity/SchoolRepository.java
Labels: fix, 의제🩳

#75 YEL-51 [fix] 타이머 수정
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/friend/dto/response/FriendResponse.java
  src/main/java/com/yello/server/domain/friend/dto/response/RecommendFriendResponse.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
  src/main/java/com/yello/server/global/common/util/TimeUtil.java
Labels: fix, 현정👕

#78 YEL-51 [hotfix] 타이머 오류해결
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: fix, 현정👕

#79 YEL-48 [feat] pay change check
  src/main/java/com/yello/server/domain/pay/controller/PayController.java
  src/main/java/com/yello/server/domain/pay/dto/request/PayCountRequest.java
  src/main/java/com/yello/server/domain/pay/entity/Pay.java
  src/main/java/com/yello/server/domain/pay/entity/PayRepository.java
  src/main/java/com/yello/server/domain/pay/sevice/PayService.java
  src/main/java/com/yello/server/domain/pay/sevice/PayServiceImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
Labels: feat, 현정👕

#80 YEL-7 [develop] 배포
  src/main/java/com/yello/server/domain/pay/controller/PayController.java
  src/main/java/com/yello/server/domain/pay/dto/request/PayCountRequest.java
  src/main/java/com/yello/server/domain/pay/entity/Pay.java
  src/main/java/com/yello/server/domain/pay/entity/PayRepository.java
  src/main/java/com/yello/server/domain/pay/sevice/PayService.java
  src/main/java/com/yello/server/domain/pay/sevice/PayServiceImpl.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
Labels: 현정👕, develop

#81 YEL-45 [docs] 스웨거 추가
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
Labels: docs, 세훈🧦

#87 YEL-51 [hotfix] 이름 부분확인 index dto 추가
  src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
  src/main/java/com/yello/server/domain/cooldown/response/RevealNameResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: fix, 현정👕

#88 YEL-5 [develop] 배포
  src/main/java/com/yello/server/domain/cooldown/response/RevealNameResponse.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: fix, 현정👕

#89 YEL-51 [hotfix] keyword hint point 반영
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
Labels: fix, feat, 현정👕

#90 YEL-45 [fix] 투표 읽음 처리
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: fix, 세훈🧦

#92 YEL-51 [hotfix] recommendId null -> ""으로 수정
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
Labels: fix, 의제🩳

#93 YEL-51 [fix] point weight 수정
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/user/entity/User.java
  src/main/java/com/yello/server/domain/vote/common/WeightedRandom.java
  src/main/java/com/yello/server/global/common/util/ConstantUtil.java
Labels: fix, 현정👕

#95 YEL-49 토큰 재발급 API 구현
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
  src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/domain/authorization/configuration/WebMvcConfig.java
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/ServiceTokenVO.java
  src/main/java/com/yello/server/domain/authorization/exception/NotExpiredTokenForbiddenException.java
  src/main/java/com/yello/server/domain/authorization/exception/NotValidTokenForbiddenException.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/annotation/ServiceToken.java
  src/main/java/com/yello/server/global/common/annotation/ServiceTokenResolver.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: feat, 의제🩳

#96 YEL-7 [DEPOLY] 0.0.3
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
  src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
  src/main/java/com/yello/server/domain/authorization/configuration/WebMvcConfig.java
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/ServiceTokenVO.java
  src/main/java/com/yello/server/domain/authorization/exception/NotExpiredTokenForbiddenException.java
  src/main/java/com/yello/server/domain/authorization/exception/NotValidTokenForbiddenException.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
  src/main/java/com/yello/server/global/common/SuccessCode.java
  src/main/java/com/yello/server/global/common/annotation/ServiceToken.java
  src/main/java/com/yello/server/global/common/annotation/ServiceTokenResolver.java
  src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
Labels: 배포 🚀

#97 YEL-51 [hotfix] 카카오추천 친구 uuid 없는 값일경우 에러처리 제거
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
Labels: fix, 현정👕

#98 YEL-51 [hotfix] 학번 추가, 온보딩 친구 추가 수정
  src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
  src/main/java/com/yello/server/domain/authorization/dto/response/OnBoardingFriendResponse.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/friend/dto/response/FriendResponse.java
Labels: fix, 의제🩳, 배포 🚀

#100 YEL-51 [fix] 친구 추가 에러 해결
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
Labels: fix, 의제🩳, 배포 🚀

#104 YEL-51 [fix] point 기본값 수정
  src/main/java/com/yello/server/domain/user/entity/User.java
Labels: feat, 현정👕

#105 YEL-7 [deveop] 서버 배포
  src/main/java/com/yello/server/domain/user/entity/User.java
Labels: 현정👕, develop

#106 YEL-51 [fix] accessToken 기간 수정
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
Labels: fix, 현정👕

#108 YEL-51 [fix] accessToekn 3minute로
  src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
Labels: fix, develop

#118 YEL-68 [hotfix] 토큰 재발급 로직 수정
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
Labels: fix, 세훈🧦, 배포 🚀

#120 YEL-72 [add] 서버 모니터링 시스템 구축
  .gitignore
  build.gradle
  monitoring/docker-compose.monitor.yml
  monitoring/prometheus/config/prometheus.yml
  src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
Labels: add, 세훈🧦, 배포 🚀

#119 YEL-70 [docs] 스웨거 개선
  build.gradle
  src/main/java/com/yello/server/domain/friend/controller/FriendController.java
  src/main/java/com/yello/server/domain/pay/controller/PayController.java
  src/main/java/com/yello/server/domain/user/controller/UserController.java
  src/main/java/com/yello/server/domain/vote/controller/VoteController.java
  src/main/java/com/yello/server/global/common/annotation/AccessTokenUser.java
  src/main/java/com/yello/server/global/configuration/SwaggerConfiguration.java
Labels: add, docs, modify, 세훈🧦

#123 YEL-74 [refactor] Vote Repository 추상화 작업
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/domain/vote/entity/Vote.java
  src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
  src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
Labels: refactor, 세훈🧦

#126 YEL-63 [fix] 중복된 투표 에러처리
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/main/java/com/yello/server/global/common/ErrorCode.java
Labels: fix, 현정👕

#125 YEL-55 [test] UserService small 테스트 추가
  src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownJpaRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
  src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
  src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
  src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepository.java
  src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
  src/test/java/com/yello/server/integration/friend/FriendControllerTest.java
  src/test/java/com/yello/server/small/cooldown/FakeCooldownRepository.java
  src/test/java/com/yello/server/small/friend/FakeFriendRepository.java
  src/test/java/com/yello/server/small/user/FakeUserRepository.java
  src/test/java/com/yello/server/small/user/UserServiceTest.java
  src/test/java/com/yello/server/small/vote/FakeVoteRepository.java
Labels: refactor, 세훈🧦, test

#127 YEL-76 [refactor] GroupRepository 추상화, service 추상화 제거
  src/main/java/com/yello/server/domain/authorization/service/AuthService.java
  src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
  src/main/java/com/yello/server/domain/friend/service/FriendService.java
  src/main/java/com/yello/server/domain/group/repository/SchoolJpaRepository.java
  src/main/java/com/yello/server/domain/group/repository/SchoolRepository.java
  src/main/java/com/yello/server/domain/group/repository/SchoolRepositoryImpl.java
  src/main/java/com/yello/server/domain/pay/sevice/PayService.java
  src/main/java/com/yello/server/domain/pay/sevice/PayServiceImpl.java
  src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
  src/main/java/com/yello/server/domain/user/service/UserService.java
  src/main/java/com/yello/server/domain/vote/service/VoteService.java
Labels: refactor, 현정👕
